/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kid.s.educational.game;

import javax.swing.ImageIcon;

/**
 *
 * @author Huong Ly
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Boolean Check = false;

    public Home() {
        super("MATH IS FUN!!!!!");
        this.setIconImage(new ImageIcon("src/Database/Background/SmallIcon.png").getImage());
        initComponents();
        Help.InputData();
        if (Help.HomeIsOn == false) {
            jButton1.setVisible(false);
                jLabel1.setIcon(Help.imgicn("src/Database/Background/Welcoming.jpg", 1030, 570));
            if (Help.Sound) {
                VoiceThread v1 = new VoiceThread(0, "Welcoming.mp3", 6500);
                v1.start();
                ThreadWelcomeFrame w2 = new ThreadWelcomeFrame("Welcoming1.jpg", 2300, jLabel1);
                ThreadWelcomeFrame w3 = new ThreadWelcomeFrame("Welcoming2.jpg", 2700, jLabel1);
                ThreadWelcomeFrame w4 = new ThreadWelcomeFrame("HomeBackground.jpeg", 3050, jLabel1);
                w2.start();
                w3.start();
                w4.start();
                btnThread h = new btnThread(4000, jButton1);
                h.start();
            } else {
                ThreadWelcomeFrame w4 = new ThreadWelcomeFrame("HomeBackground.jpeg", 1500, jLabel1);btnThread h = new btnThread(1500, jButton1);
                h.start();
                w4.start();
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1026, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/Background/StartBtn.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 230, 170, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/Background/HomeBackground.jpeg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setPreferredSize(new java.awt.Dimension(1025, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static VoiceThread v2 = new VoiceThread(0, "ThemeMusic.mp3", 871000);
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new GameChoosing().setVisible(true);
        if (Help.Sound && Help.HomeIsOn == false) {
            v2.setRepeat(true);
            v2.start();
        }
        Help.HomeIsOn = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
